component umi {
	chdir "/umi";
$$iftrue RUN_MORBO
	command "morbo -f script/umi";
$$else
	command "hypnotoad -f script/umi";
$$endif
	stderr ${PIES_SYSLOG_SERVER:|syslog daemon.err|file /proc/1/fd/2};
	stdout ${PIES_SYSLOG_SERVER:|syslog daemon.info|file /proc/1/fd/1};
}
