#-*- mode: cperlx; eval: (follow-mode) -*-

package Umi::Constants;

use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(
    COUNTRIES
    );

use constant {
	      # ISO 5218 Representation of human sex
	      GENDER => {
			 0 => 'Not known',
			 1 => 'Male',
			 2 => 'Female',
			 9 => 'Not applicable',
			},
	      # ISO 3166 country codes
	      COUNTRIES => {
			    AF => { three =>'AFG', num => '004', name => 'Afghanistan' },
			    AL => { three =>'ALB', num => '008', name => 'Albania' },
			    AX => { three =>'ALA', num => '248', name => 'Åland Islands' },
			    DZ => { three =>'DZA', num => '012', name => 'Algeria' },
			    AS => { three =>'ASM', num => '016', name => 'American Samoa' },
			    AD => { three =>'AND', num => '020', name => 'Andorra' },
			    AO => { three =>'AGO', num => '024', name => 'Angola' },
			    AI => { three =>'AIA', num => '660', name => 'Anguilla' },
			    AQ => { three =>'ATA', num => '010', name => 'Antarctica' },
			    AG => { three =>'ATG', num => '028', name => 'Antigua and Barbuda' },
			    AR => { three =>'ARG', num => '032', name => 'Argentina' },
			    AM => { three =>'ARM', num => '051', name => 'Armenia' },
			    AW => { three =>'ABW', num => '533', name => 'Aruba' },
			    AU => { three =>'AUS', num => '036', name => 'Australia' },
			    AT => { three =>'AUT', num => '040', name => 'Austria' },
			    AZ => { three =>'AZE', num => '031', name => 'Azerbaijan' },
			    BS => { three =>'BHS', num => '044', name => 'Bahamas' },
			    BH => { three =>'BHR', num => '048', name => 'Bahrain' },
			    BD => { three =>'BGD', num => '050', name => 'Bangladesh' },
			    BB => { three =>'BRB', num => '052', name => 'Barbados' },
			    BY => { three =>'BLR', num => '112', name => 'Belarus' },
			    BE => { three =>'BEL', num => '056', name => 'Belgium' },
			    BZ => { three =>'BLZ', num => '084', name => 'Belize' },
			    BJ => { three =>'BEN', num => '204', name => 'Benin' },
			    BM => { three =>'BMU', num => '060', name => 'Bermuda' },
			    BT => { three =>'BTN', num => '064', name => 'Bhutan' },
			    BO => { three =>'BOL', num => '068', name => 'Bolivia, Plurinational State of' },
			    BQ => { three =>'BES', num => '535', name => 'Bonaire, Sint Eustatius and Saba' },
			    BA => { three =>'BIH', num => '070', name => 'Bosnia and Herzegovina' },
			    BW => { three =>'BWA', num => '072', name => 'Botswana' },
			    BV => { three =>'BVT', num => '074', name => 'Bouvet Island' },
			    BR => { three =>'BRA', num => '076', name => 'Brazil' },
			    IO => { three =>'IOT', num => '086', name => 'British Indian Ocean Territory' },
			    BN => { three =>'BRN', num => '096', name => 'Brunei Darussalam' },
			    BG => { three =>'BGR', num => '100', name => 'Bulgaria' },
			    BF => { three =>'BFA', num => '854', name => 'Burkina Faso' },
			    BI => { three =>'BDI', num => '108', name => 'Burundi' },
			    KH => { three =>'KHM', num => '116', name => 'Cambodia' },
			    CM => { three =>'CMR', num => '120', name => 'Cameroon' },
			    CA => { three =>'CAN', num => '124', name => 'Canada' },
			    CV => { three =>'CPV', num => '132', name => 'Cabo Verde' },
			    KY => { three =>'CYM', num => '136', name => 'Cayman Islands' },
			    CF => { three =>'CAF', num => '140', name => 'Central African Republic' },
			    TD => { three =>'TCD', num => '148', name => 'Chad' },
			    CL => { three =>'CHL', num => '152', name => 'Chile' },
			    CN => { three =>'CHN', num => '156', name => 'China' },
			    CX => { three =>'CXR', num => '162', name => 'Christmas Island' },
			    CC => { three =>'CCK', num => '166', name => 'Cocos (Keeling) Islands' },
			    CO => { three =>'COL', num => '170', name => 'Colombia' },
			    KM => { three =>'COM', num => '174', name => 'Comoros' },
			    CG => { three =>'COG', num => '178', name => 'Congo' },
			    CD => { three =>'COD', num => '180', name => 'Congo, Democratic Republic of the' },
			    CK => { three =>'COK', num => '184', name => 'Cook Islands' },
			    CR => { three =>'CRI', num => '188', name => 'Costa Rica' },
			    CI => { three =>'CIV', num => '384', name => 'Côte d\'Ivoire' },
			    HR => { three =>'HRV', num => '191', name => 'Croatia' },
			    CU => { three =>'CUB', num => '192', name => 'Cuba' },
			    CW => { three =>'CUW', num => '531', name => 'Curaçao' },
			    CY => { three =>'CYP', num => '196', name => 'Cyprus' },
			    CZ => { three =>'CZE', num => '203', name => 'Czech Republic' },
			    DK => { three =>'DNK', num => '208', name => 'Denmark' },
			    DJ => { three =>'DJI', num => '262', name => 'Djibouti' },
			    DM => { three =>'DMA', num => '212', name => 'Dominica' },
			    DO => { three =>'DOM', num => '214', name => 'Dominican Republic' },
			    EC => { three =>'ECU', num => '218', name => 'Ecuador' },
			    EG => { three =>'EGY', num => '818', name => 'Egypt' },
			    SV => { three =>'SLV', num => '222', name => 'El Salvador' },
			    GQ => { three =>'GNQ', num => '226', name => 'Equatorial Guinea' },
			    ER => { three =>'ERI', num => '232', name => 'Eritrea' },
			    EE => { three =>'EST', num => '233', name => 'Estonia' },
			    ET => { three =>'ETH', num => '231', name => 'Ethiopia' },
			    FK => { three =>'FLK', num => '238', name => 'Falkland Islands (Malvinas)' },
			    FO => { three =>'FRO', num => '234', name => 'Faroe Islands' },
			    FJ => { three =>'FJI', num => '242', name => 'Fiji' },
			    FI => { three =>'FIN', num => '246', name => 'Finland' },
			    FR => { three =>'FRA', num => '250', name => 'France' },
			    GF => { three =>'GUF', num => '254', name => 'French Guiana' },
			    PF => { three =>'PYF', num => '258', name => 'French Polynesia' },
			    TF => { three =>'ATF', num => '260', name => 'French Southern Territories' },
			    GA => { three =>'GAB', num => '266', name => 'Gabon' },
			    GM => { three =>'GMB', num => '270', name => 'Gambia' },
			    GE => { three =>'GEO', num => '268', name => 'Georgia' },
			    DE => { three =>'DEU', num => '276', name => 'Germany' },
			    GH => { three =>'GHA', num => '288', name => 'Ghana' },
			    GI => { three =>'GIB', num => '292', name => 'Gibraltar' },
			    GR => { three =>'GRC', num => '300', name => 'Greece' },
			    GL => { three =>'GRL', num => '304', name => 'Greenland' },
			    GD => { three =>'GRD', num => '308', name => 'Grenada' },
			    GP => { three =>'GLP', num => '312', name => 'Guadeloupe' },
			    GU => { three =>'GUM', num => '316', name => 'Guam' },
			    GT => { three =>'GTM', num => '320', name => 'Guatemala' },
			    GG => { three =>'GGY', num => '831', name => 'Guernsey' },
			    GN => { three =>'GIN', num => '324', name => 'Guinea' },
			    GW => { three =>'GNB', num => '624', name => 'Guinea-Bissau' },
			    GY => { three =>'GUY', num => '328', name => 'Guyana' },
			    HT => { three =>'HTI', num => '332', name => 'Haiti' },
			    HM => { three =>'HMD', num => '334', name => 'Heard Island and McDonald Islands' },
			    VA => { three =>'VAT', num => '336', name => 'Holy See' },
			    HN => { three =>'HND', num => '340', name => 'Honduras' },
			    HK => { three =>'HKG', num => '344', name => 'Hong Kong' },
			    HU => { three =>'HUN', num => '348', name => 'Hungary' },
			    IS => { three =>'ISL', num => '352', name => 'Iceland' },
			    IN => { three =>'IND', num => '356', name => 'India' },
			    ID => { three =>'IDN', num => '360', name => 'Indonesia' },
			    IR => { three =>'IRN', num => '364', name => 'Iran (Islamic Republic of)' },
			    IQ => { three =>'IRQ', num => '368', name => 'Iraq' },
			    IE => { three =>'IRL', num => '372', name => 'Ireland' },
			    IM => { three =>'IMN', num => '833', name => 'Isle of Man' },
			    IL => { three =>'ISR', num => '376', name => 'Israel' },
			    IT => { three =>'ITA', num => '380', name => 'Italy' },
			    JM => { three =>'JAM', num => '388', name => 'Jamaica' },
			    JP => { three =>'JPN', num => '392', name => 'Japan' },
			    JE => { three =>'JEY', num => '832', name => 'Jersey' },
			    JO => { three =>'JOR', num => '400', name => 'Jordan' },
			    KZ => { three =>'KAZ', num => '398', name => 'Kazakhstan' },
			    KE => { three =>'KEN', num => '404', name => 'Kenya' },
			    KI => { three =>'KIR', num => '296', name => 'Kiribati' },
			    KP => { three =>'PRK', num => '408', name => 'Korea (Democratic People\'s Republic of)' },
			    KR => { three =>'KOR', num => '410', name => 'Korea (Republic of)' },
			    KW => { three =>'KWT', num => '414', name => 'Kuwait' },
			    KG => { three =>'KGZ', num => '417', name => 'Kyrgyzstan' },
			    LA => { three =>'LAO', num => '418', name => 'Lao People\'s Democratic Republic' },
			    LV => { three =>'LVA', num => '428', name => 'Latvia' },
			    LB => { three =>'LBN', num => '422', name => 'Lebanon' },
			    LS => { three =>'LSO', num => '426', name => 'Lesotho' },
			    LR => { three =>'LBR', num => '430', name => 'Liberia' },
			    LY => { three =>'LBY', num => '434', name => 'Libya' },
			    LI => { three =>'LIE', num => '438', name => 'Liechtenstein' },
			    LT => { three =>'LTU', num => '440', name => 'Lithuania' },
			    LU => { three =>'LUX', num => '442', name => 'Luxembourg' },
			    MO => { three =>'MAC', num => '446', name => 'Macao' },
			    MK => { three =>'MKD', num => '807', name => 'Macedonia (the former Yugoslav Republic of)' },
			    MG => { three =>'MDG', num => '450', name => 'Madagascar' },
			    MW => { three =>'MWI', num => '454', name => 'Malawi' },
			    MY => { three =>'MYS', num => '458', name => 'Malaysia' },
			    MV => { three =>'MDV', num => '462', name => 'Maldives' },
			    ML => { three =>'MLI', num => '466', name => 'Mali' },
			    MT => { three =>'MLT', num => '470', name => 'Malta' },
			    MH => { three =>'MHL', num => '584', name => 'Marshall Islands' },
			    MQ => { three =>'MTQ', num => '474', name => 'Martinique' },
			    MR => { three =>'MRT', num => '478', name => 'Mauritania' },
			    MU => { three =>'MUS', num => '480', name => 'Mauritius' },
			    YT => { three =>'MYT', num => '175', name => 'Mayotte' },
			    MX => { three =>'MEX', num => '484', name => 'Mexico' },
			    FM => { three =>'FSM', num => '583', name => 'Micronesia (Federated States of)' },
			    MD => { three =>'MDA', num => '498', name => 'Moldova (Republic of)' },
			    MC => { three =>'MCO', num => '492', name => 'Monaco' },
			    MN => { three =>'MNG', num => '496', name => 'Mongolia' },
			    ME => { three =>'MNE', num => '499', name => 'Montenegro' },
			    MS => { three =>'MSR', num => '500', name => 'Montserrat' },
			    MA => { three =>'MAR', num => '504', name => 'Morocco' },
			    MZ => { three =>'MOZ', num => '508', name => 'Mozambique' },
			    MM => { three =>'MMR', num => '104', name => 'Myanmar' },
			    NA => { three =>'NAM', num => '516', name => 'Namibia' },
			    NR => { three =>'NRU', num => '520', name => 'Nauru' },
			    NP => { three =>'NPL', num => '524', name => 'Nepal' },
			    NL => { three =>'NLD', num => '528', name => 'Netherlands' },
			    NC => { three =>'NCL', num => '540', name => 'New Caledonia' },
			    NZ => { three =>'NZL', num => '554', name => 'New Zealand' },
			    NI => { three =>'NIC', num => '558', name => 'Nicaragua' },
			    NE => { three =>'NER', num => '562', name => 'Niger' },
			    NG => { three =>'NGA', num => '566', name => 'Nigeria' },
			    NU => { three =>'NIU', num => '570', name => 'Niue' },
			    NF => { three =>'NFK', num => '574', name => 'Norfolk Island' },
			    MP => { three =>'MNP', num => '580', name => 'Northern Mariana Islands' },
			    NO => { three =>'NOR', num => '578', name => 'Norway' },
			    OM => { three =>'OMN', num => '512', name => 'Oman' },
			    PK => { three =>'PAK', num => '586', name => 'Pakistan' },
			    PW => { three =>'PLW', num => '585', name => 'Palau' },
			    PS => { three =>'PSE', num => '275', name => 'Palestine, State of' },
			    PA => { three =>'PAN', num => '591', name => 'Panama' },
			    PG => { three =>'PNG', num => '598', name => 'Papua New Guinea' },
			    PY => { three =>'PRY', num => '600', name => 'Paraguay' },
			    PE => { three =>'PER', num => '604', name => 'Peru' },
			    PH => { three =>'PHL', num => '608', name => 'Philippines' },
			    PN => { three =>'PCN', num => '612', name => 'Pitcairn' },
			    PL => { three =>'POL', num => '616', name => 'Poland' },
			    PT => { three =>'PRT', num => '620', name => 'Portugal' },
			    PR => { three =>'PRI', num => '630', name => 'Puerto Rico' },
			    QA => { three =>'QAT', num => '634', name => 'Qatar' },
			    RE => { three =>'REU', num => '638', name => 'Réunion' },
			    RO => { three =>'ROU', num => '642', name => 'Romania' },
			    RU => { three =>'RUS', num => '643', name => 'Russian Federation' },
			    RW => { three =>'RWA', num => '646', name => 'Rwanda' },
			    BL => { three =>'BLM', num => '652', name => 'Saint Barthélemy' },
			    SH => { three =>'SHN', num => '654', name => 'Saint Helena Ascension and Tristan da Cunha' },
			    KN => { three =>'KNA', num => '659', name => 'Saint Kitts and Nevis' },
			    LC => { three =>'LCA', num => '662', name => 'Saint Lucia' },
			    MF => { three =>'MAF', num => '663', name => 'Saint Martin (French part)' },
			    PM => { three =>'SPM', num => '666', name => 'Saint Pierre and Miquelon' },
			    VC => { three =>'VCT', num => '670', name => 'Saint Vincent and the Grenadines' },
			    WS => { three =>'WSM', num => '882', name => 'Samoa' },
			    SM => { three =>'SMR', num => '674', name => 'San Marino' },
			    ST => { three =>'STP', num => '678', name => 'Sao Tome and Principe' },
			    SA => { three =>'SAU', num => '682', name => 'Saudi Arabia' },
			    SN => { three =>'SEN', num => '686', name => 'Senegal' },
			    RS => { three =>'SRB', num => '688', name => 'Serbia' },
			    SC => { three =>'SYC', num => '690', name => 'Seychelles' },
			    SL => { three =>'SLE', num => '694', name => 'Sierra Leone' },
			    SG => { three =>'SGP', num => '702', name => 'Singapore' },
			    SX => { three =>'SXM', num => '534', name => 'Sint Maarten (Dutch part)' },
			    SK => { three =>'SVK', num => '703', name => 'Slovakia' },
			    SI => { three =>'SVN', num => '705', name => 'Slovenia' },
			    SB => { three =>'SLB', num => '090', name => 'Solomon Islands' },
			    SO => { three =>'SOM', num => '706', name => 'Somalia' },
			    ZA => { three =>'ZAF', num => '710', name => 'South Africa' },
			    GS => { three =>'SGS', num => '239', name => 'South Georgia and the South Sandwich Islands' },
			    SS => { three =>'SSD', num => '728', name => 'South Sudan' },
			    ES => { three =>'ESP', num => '724', name => 'Spain' },
			    LK => { three =>'LKA', num => '144', name => 'Sri Lanka' },
			    SD => { three =>'SDN', num => '729', name => 'Sudan' },
			    SR => { three =>'SUR', num => '740', name => 'Suriname' },
			    SJ => { three =>'SJM', num => '744', name => 'Svalbard and Jan Mayen' },
			    SZ => { three =>'SWZ', num => '748', name => 'Eswatini' },
			    SE => { three =>'SWE', num => '752', name => 'Sweden' },
			    CH => { three =>'CHE', num => '756', name => 'Switzerland' },
			    SY => { three =>'SYR', num => '760', name => 'Syrian Arab Republic' },
			    TW => { three =>'TWN', num => '158', name => 'Taiwan' },
			    TJ => { three =>'TJK', num => '762', name => 'Tajikistan' },
			    TZ => { three =>'TZA', num => '834', name => 'Tanzania United Republic of' },
			    TH => { three =>'THA', num => '764', name => 'Thailand' },
			    TL => { three =>'TLS', num => '626', name => 'Timor-Leste' },
			    TG => { three =>'TGO', num => '768', name => 'Togo' },
			    TK => { three =>'TKL', num => '772', name => 'Tokelau' },
			    TO => { three =>'TON', num => '776', name => 'Tonga' },
			    TT => { three =>'TTO', num => '780', name => 'Trinidad and Tobago' },
			    TN => { three =>'TUN', num => '788', name => 'Tunisia' },
			    TR => { three =>'TUR', num => '792', name => 'Turkey' },
			    TM => { three =>'TKM', num => '795', name => 'Turkmenistan' },
			    TC => { three =>'TCA', num => '796', name => 'Turks and Caicos Islands' },
			    TV => { three =>'TUV', num => '798', name => 'Tuvalu' },
			    UG => { three =>'UGA', num => '800', name => 'Uganda' },
			    UA => { three =>'UKR', num => '804', name => 'Ukraine' },
			    AE => { three =>'ARE', num => '784', name => 'United Arab Emirates' },
			    GB => { three =>'GBR', num => '826', name => 'United Kingdom of Great Britain and Northern Ireland' },
			    US => { three =>'USA', num => '840', name => 'United States of America' },
			    UM => { three =>'UMI', num => '581', name => 'United States Minor Outlying Islands' },
			    UY => { three =>'URY', num => '858', name => 'Uruguay' },
			    UZ => { three =>'UZB', num => '860', name => 'Uzbekistan' },
			    VU => { three =>'VUT', num => '548', name => 'Vanuatu' },
			    VE => { three =>'VEN', num => '862', name => 'Venezuela, Bolivarian Republic of' },
			    VN => { three =>'VNM', num => '704', name => 'Viet Nam' },
			    VG => { three =>'VGB', num => '092', name => 'Virgin Islands (British)' },
			    VI => { three =>'VIR', num => '850', name => 'Virgin Islands (U.S.)' },
			    WF => { three =>'WLF', num => '876', name => 'Wallis and Futuna' },
			    EH => { three =>'ESH', num => '732', name => 'Western Sahara' },
			    YE => { three =>'YEM', num => '887', name => 'Yemen' },
			    ZM => { three =>'ZMB', num => '894', name => 'Zambia' },
			    ZW => { three =>'ZWE', num => '716', name => 'Zimbabwe' },
			   }
	     };

1;
