#-*- mode: cperl; eval: (follow-mode) -*-

package Umi::Constants;

use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(
    COUNTRIES
    );

use constant {
	      UMIOVPNADDSTATUS => {
				disabled => 0,
				enabled => 1
			       },
	      UMIOVPNADDDEVTYPE => [qw( notebook macbook wrt desktop phone other )],
	      UMIOVPNADDDEVOS => [qw( windows unix macos ios android other )],
	      # ISO 5218 Representation of human sex
	      GENDER => {
			 0 => 'Not known',
			 1 => 'Male',
			 2 => 'Female',
			 9 => 'Not applicable',
			},
	      # ISO 3166 country codes
	      COUNTRIES => {
			    'Afghanistan' 						  => { two => 'AF', three =>'AFG', num => '004' },
			    'Albania' 						  => { two => 'AL', three =>'ALB', num => '008' },
			    'Åland Islands' 						  => { two => 'AX', three =>'ALA', num => '248' },
			    'Algeria' 						  => { two => 'DZ', three =>'DZA', num => '012' },
			    'American Samoa' 						  => { two => 'AS', three =>'ASM', num => '016' },
			    'Andorra' 						  => { two => 'AD', three =>'AND', num => '020' },
			    'Angola' 							  => { two => 'AO', three =>'AGO', num => '024' },
			    'Anguilla' 						  => { two => 'AI', three =>'AIA', num => '660' },
			    'Antarctica' 						  => { two => 'AQ', three =>'ATA', num => '010' },
			    'Antigua and Barbuda' 					  => { two => 'AG', three =>'ATG', num => '028' },
			    'Argentina' 						  => { two => 'AR', three =>'ARG', num => '032' },
			    'Armenia' 						  => { two => 'AM', three =>'ARM', num => '051' },
			    'Aruba' 							  => { two => 'AW', three =>'ABW', num => '533' },
			    'Australia' 						  => { two => 'AU', three =>'AUS', num => '036' },
			    'Austria' 						  => { two => 'AT', three =>'AUT', num => '040' },
			    'Azerbaijan' 						  => { two => 'AZ', three =>'AZE', num => '031' },
			    'Bahamas' 						  => { two => 'BS', three =>'BHS', num => '044' },
			    'Bahrain' 						  => { two => 'BH', three =>'BHR', num => '048' },
			    'Bangladesh' 						  => { two => 'BD', three =>'BGD', num => '050' },
			    'Barbados' 						  => { two => 'BB', three =>'BRB', num => '052' },
			    'Belarus' 						  => { two => 'BY', three =>'BLR', num => '112' },
			    'Belgium' 						  => { two => 'BE', three =>'BEL', num => '056' },
			    'Belize' 							  => { two => 'BZ', three =>'BLZ', num => '084' },
			    'Benin' 							  => { two => 'BJ', three =>'BEN', num => '204' },
			    'Bermuda' 						  => { two => 'BM', three =>'BMU', num => '060' },
			    'Bhutan' 							  => { two => 'BT', three =>'BTN', num => '064' },
			    'Bolivia, Plurinational State of' 			  => { two => 'BO', three =>'BOL', num => '068' },
			    'Bonaire, Sint Eustatius and Saba' 			  => { two => 'BQ', three =>'BES', num => '535' },
			    'Bosnia and Herzegovina' 					  => { two => 'BA', three =>'BIH', num => '070' },
			    'Botswana' 						  => { two => 'BW', three =>'BWA', num => '072' },
			    'Bouvet Island' 						  => { two => 'BV', three =>'BVT', num => '074' },
			    'Brazil' 							  => { two => 'BR', three =>'BRA', num => '076' },
			    'British Indian Ocean Territory' 				  => { two => 'IO', three =>'IOT', num => '086' },
			    'Brunei Darussalam' 					  => { two => 'BN', three =>'BRN', num => '096' },
			    'Bulgaria' 						  => { two => 'BG', three =>'BGR', num => '100' },
			    'Burkina Faso' 						  => { two => 'BF', three =>'BFA', num => '854' },
			    'Burundi' 						  => { two => 'BI', three =>'BDI', num => '108' },
			    'Cambodia' 						  => { two => 'KH', three =>'KHM', num => '116' },
			    'Cameroon' 						  => { two => 'CM', three =>'CMR', num => '120' },
			    'Canada' 							  => { two => 'CA', three =>'CAN', num => '124' },
			    'Cabo Verde' 						  => { two => 'CV', three =>'CPV', num => '132' },
			    'Cayman Islands' 						  => { two => 'KY', three =>'CYM', num => '136' },
			    'Central African Republic' 				  => { two => 'CF', three =>'CAF', num => '140' },
			    'Chad' 							  => { two => 'TD', three =>'TCD', num => '148' },
			    'Chile' 							  => { two => 'CL', three =>'CHL', num => '152' },
			    'China' 							  => { two => 'CN', three =>'CHN', num => '156' },
			    'Christmas Island' 					  => { two => 'CX', three =>'CXR', num => '162' },
			    'Cocos (Keeling) Islands' 				  => { two => 'CC', three =>'CCK', num => '166' },
			    'Colombia' 						  => { two => 'CO', three =>'COL', num => '170' },
			    'Comoros' 						  => { two => 'KM', three =>'COM', num => '174' },
			    'Congo' 							  => { two => 'CG', three =>'COG', num => '178' },
			    'Congo, Democratic Republic of the' 			  => { two => 'CD', three =>'COD', num => '180' },
			    'Cook Islands' 						  => { two => 'CK', three =>'COK', num => '184' },
			    'Costa Rica' 						  => { two => 'CR', three =>'CRI', num => '188' },
			    'Côte d\'Ivoire' 						  => { two => 'CI', three =>'CIV', num => '384' },
			    'Croatia' 						  => { two => 'HR', three =>'HRV', num => '191' },
			    'Cuba' 							  => { two => 'CU', three =>'CUB', num => '192' },
			    'Curaçao' 						  => { two => 'CW', three =>'CUW', num => '531' },
			    'Cyprus' 							  => { two => 'CY', three =>'CYP', num => '196' },
			    'Czech Republic' 						  => { two => 'CZ', three =>'CZE', num => '203' },
			    'Denmark' 						  => { two => 'DK', three =>'DNK', num => '208' },
			    'Djibouti' 						  => { two => 'DJ', three =>'DJI', num => '262' },
			    'Dominica' 						  => { two => 'DM', three =>'DMA', num => '212' },
			    'Dominican Republic' 					  => { two => 'DO', three =>'DOM', num => '214' },
			    'Ecuador' 						  => { two => 'EC', three =>'ECU', num => '218' },
			    'Egypt' 							  => { two => 'EG', three =>'EGY', num => '818' },
			    'El Salvador' 						  => { two => 'SV', three =>'SLV', num => '222' },
			    'Equatorial Guinea' 					  => { two => 'GQ', three =>'GNQ', num => '226' },
			    'Eritrea' 						  => { two => 'ER', three =>'ERI', num => '232' },
			    'Estonia' 						  => { two => 'EE', three =>'EST', num => '233' },
			    'Ethiopia' 						  => { two => 'ET', three =>'ETH', num => '231' },
			    'Falkland Islands (Malvinas)' 				  => { two => 'FK', three =>'FLK', num => '238' },
			    'Faroe Islands' 						  => { two => 'FO', three =>'FRO', num => '234' },
			    'Fiji' 							  => { two => 'FJ', three =>'FJI', num => '242' },
			    'Finland' 						  => { two => 'FI', three =>'FIN', num => '246' },
			    'France' 							  => { two => 'FR', three =>'FRA', num => '250' },
			    'French Guiana' 						  => { two => 'GF', three =>'GUF', num => '254' },
			    'French Polynesia' 					  => { two => 'PF', three =>'PYF', num => '258' },
			    'French Southern Territories' 				  => { two => 'TF', three =>'ATF', num => '260' },
			    'Gabon' 							  => { two => 'GA', three =>'GAB', num => '266' },
			    'Gambia' 							  => { two => 'GM', three =>'GMB', num => '270' },
			    'Georgia' 						  => { two => 'GE', three =>'GEO', num => '268' },
			    'Germany' 						  => { two => 'DE', three =>'DEU', num => '276' },
			    'Ghana' 							  => { two => 'GH', three =>'GHA', num => '288' },
			    'Gibraltar' 						  => { two => 'GI', three =>'GIB', num => '292' },
			    'Greece' 							  => { two => 'GR', three =>'GRC', num => '300' },
			    'Greenland' 						  => { two => 'GL', three =>'GRL', num => '304' },
			    'Grenada' 						  => { two => 'GD', three =>'GRD', num => '308' },
			    'Guadeloupe' 						  => { two => 'GP', three =>'GLP', num => '312' },
			    'Guam' 							  => { two => 'GU', three =>'GUM', num => '316' },
			    'Guatemala' 						  => { two => 'GT', three =>'GTM', num => '320' },
			    'Guernsey' 						  => { two => 'GG', three =>'GGY', num => '831' },
			    'Guinea' 							  => { two => 'GN', three =>'GIN', num => '324' },
			    'Guinea-Bissau' 						  => { two => 'GW', three =>'GNB', num => '624' },
			    'Guyana' 							  => { two => 'GY', three =>'GUY', num => '328' },
			    'Haiti' 							  => { two => 'HT', three =>'HTI', num => '332' },
			    'Heard Island and McDonald Islands' 			  => { two => 'HM', three =>'HMD', num => '334' },
			    'Holy See' 						  => { two => 'VA', three =>'VAT', num => '336' },
			    'Honduras' 						  => { two => 'HN', three =>'HND', num => '340' },
			    'Hong Kong' 						  => { two => 'HK', three =>'HKG', num => '344' },
			    'Hungary' 						  => { two => 'HU', three =>'HUN', num => '348' },
			    'Iceland' 						  => { two => 'IS', three =>'ISL', num => '352' },
			    'India' 							  => { two => 'IN', three =>'IND', num => '356' },
			    'Indonesia' 						  => { two => 'ID', three =>'IDN', num => '360' },
			    'Iran (Islamic Republic of)' 				  => { two => 'IR', three =>'IRN', num => '364' },
			    'Iraq' 							  => { two => 'IQ', three =>'IRQ', num => '368' },
			    'Ireland' 						  => { two => 'IE', three =>'IRL', num => '372' },
			    'Isle of Man' 						  => { two => 'IM', three =>'IMN', num => '833' },
			    'Israel' 							  => { two => 'IL', three =>'ISR', num => '376' },
			    'Italy' 							  => { two => 'IT', three =>'ITA', num => '380' },
			    'Jamaica' 						  => { two => 'JM', three =>'JAM', num => '388' },
			    'Japan' 							  => { two => 'JP', three =>'JPN', num => '392' },
			    'Jersey' 							  => { two => 'JE', three =>'JEY', num => '832' },
			    'Jordan' 							  => { two => 'JO', three =>'JOR', num => '400' },
			    'Kazakhstan' 						  => { two => 'KZ', three =>'KAZ', num => '398' },
			    'Kenya' 							  => { two => 'KE', three =>'KEN', num => '404' },
			    'Kiribati' 						  => { two => 'KI', three =>'KIR', num => '296' },
			    'Korea (Democratic People\'s Republic of)' 		  => { two => 'KP', three =>'PRK', num => '408' },
			    'Korea (Republic of)' 					  => { two => 'KR', three =>'KOR', num => '410' },
			    'Kuwait' 							  => { two => 'KW', three =>'KWT', num => '414' },
			    'Kyrgyzstan' 						  => { two => 'KG', three =>'KGZ', num => '417' },
			    'Lao People\'s Democratic Republic' 			  => { two => 'LA', three =>'LAO', num => '418' },
			    'Latvia' 							  => { two => 'LV', three =>'LVA', num => '428' },
			    'Lebanon' 						  => { two => 'LB', three =>'LBN', num => '422' },
			    'Lesotho' 						  => { two => 'LS', three =>'LSO', num => '426' },
			    'Liberia' 						  => { two => 'LR', three =>'LBR', num => '430' },
			    'Libya' 							  => { two => 'LY', three =>'LBY', num => '434' },
			    'Liechtenstein' 						  => { two => 'LI', three =>'LIE', num => '438' },
			    'Lithuania' 						  => { two => 'LT', three =>'LTU', num => '440' },
			    'Luxembourg' 						  => { two => 'LU', three =>'LUX', num => '442' },
			    'Macao' 							  => { two => 'MO', three =>'MAC', num => '446' },
			    'Macedonia (the former Yugoslav Republic of)' 		  => { two => 'MK', three =>'MKD', num => '807' },
			    'Madagascar' 						  => { two => 'MG', three =>'MDG', num => '450' },
			    'Malawi' 							  => { two => 'MW', three =>'MWI', num => '454' },
			    'Malaysia' 						  => { two => 'MY', three =>'MYS', num => '458' },
			    'Maldives' 						  => { two => 'MV', three =>'MDV', num => '462' },
			    'Mali' 							  => { two => 'ML', three =>'MLI', num => '466' },
			    'Malta' 							  => { two => 'MT', three =>'MLT', num => '470' },
			    'Marshall Islands' 					  => { two => 'MH', three =>'MHL', num => '584' },
			    'Martinique' 						  => { two => 'MQ', three =>'MTQ', num => '474' },
			    'Mauritania' 						  => { two => 'MR', three =>'MRT', num => '478' },
			    'Mauritius' 						  => { two => 'MU', three =>'MUS', num => '480' },
			    'Mayotte' 						  => { two => 'YT', three =>'MYT', num => '175' },
			    'Mexico' 							  => { two => 'MX', three =>'MEX', num => '484' },
			    'Micronesia (Federated States of)' 			  => { two => 'FM', three =>'FSM', num => '583' },
			    'Moldova (Republic of)' 					  => { two => 'MD', three =>'MDA', num => '498' },
			    'Monaco' 							  => { two => 'MC', three =>'MCO', num => '492' },
			    'Mongolia' 						   => { two => 'MN', three =>'MNG', num => '496' },
			    'Montenegro' 					   => { two => 'ME', three =>'MNE', num => '499' },
			    'Montserrat' 					   => { two => 'MS', three =>'MSR', num => '500' },
			    'Morocco' 						   => { two => 'MA', three =>'MAR', num => '504' },
			    'Mozambique' 					   => { two => 'MZ', three =>'MOZ', num => '508' },
			    'Myanmar' 						   => { two => 'MM', three =>'MMR', num => '104' },
			    'Namibia' 						   => { two => 'NA', three =>'NAM', num => '516' },
			    'Nauru' 						   => { two => 'NR', three =>'NRU', num => '520' },
			    'Nepal' 						   => { two => 'NP', three =>'NPL', num => '524' },
			    'Netherlands' 					   => { two => 'NL', three =>'NLD', num => '528' },
			    'New Caledonia' 					   => { two => 'NC', three =>'NCL', num => '540' },
			    'New Zealand' 					   => { two => 'NZ', three =>'NZL', num => '554' },
			    'Nicaragua' 					   => { two => 'NI', three =>'NIC', num => '558' },
			    'Niger' 						   => { two => 'NE', three =>'NER', num => '562' },
			    'Nigeria' 						   => { two => 'NG', three =>'NGA', num => '566' },
			    'Niue' 						   => { two => 'NU', three =>'NIU', num => '570' },
			    'Norfolk Island' 					   => { two => 'NF', three =>'NFK', num => '574' },
			    'Northern Mariana Islands' 				   => { two => 'MP', three =>'MNP', num => '580' },
			    'Norway' 						   => { two => 'NO', three =>'NOR', num => '578' },
			    'Oman' 						   => { two => 'OM', three =>'OMN', num => '512' },
			    'Pakistan' 						   => { two => 'PK', three =>'PAK', num => '586' },
			    'Palau' 						   => { two => 'PW', three =>'PLW', num => '585' },
			    'Palestine, State of' 				   => { two => 'PS', three =>'PSE', num => '275' },
			    'Panama' 						   => { two => 'PA', three =>'PAN', num => '591' },
			    'Papua New Guinea' 					   => { two => 'PG', three =>'PNG', num => '598' },
			    'Paraguay' 						   => { two => 'PY', three =>'PRY', num => '600' },
			    'Peru' 						   => { two => 'PE', three =>'PER', num => '604' },
			    'Philippines' 					   => { two => 'PH', three =>'PHL', num => '608' },
			    'Pitcairn' 						   => { two => 'PN', three =>'PCN', num => '612' },
			    'Poland' 						   => { two => 'PL', three =>'POL', num => '616' },
			    'Portugal' 						   => { two => 'PT', three =>'PRT', num => '620' },
			    'Puerto Rico' 					   => { two => 'PR', three =>'PRI', num => '630' },
			    'Qatar' 						   => { two => 'QA', three =>'QAT', num => '634' },
			    'Réunion' 						   => { two => 'RE', three =>'REU', num => '638' },
			    'Romania' 						   => { two => 'RO', three =>'ROU', num => '642' },
			    'Russian Federation' 				   => { two => 'RU', three =>'RUS', num => '643' },
			    'Rwanda' 						   => { two => 'RW', three =>'RWA', num => '646' },
			    'Saint Barthélemy' 					   => { two => 'BL', three =>'BLM', num => '652' },
			    'Saint Helena Ascension and Tristan da Cunha' 	   => { two => 'SH', three =>'SHN', num => '654' },
			    'Saint Kitts and Nevis' 				   => { two => 'KN', three =>'KNA', num => '659' },
			    'Saint Lucia' 					   => { two => 'LC', three =>'LCA', num => '662' },
			    'Saint Martin (French part)' 			   => { two => 'MF', three =>'MAF', num => '663' },
			    'Saint Pierre and Miquelon' 			   => { two => 'PM', three =>'SPM', num => '666' },
			    'Saint Vincent and the Grenadines' 			   => { two => 'VC', three =>'VCT', num => '670' },
			    'Samoa' 						   => { two => 'WS', three =>'WSM', num => '882' },
			    'San Marino' 					   => { two => 'SM', three =>'SMR', num => '674' },
			    'Sao Tome and Principe' 				   => { two => 'ST', three =>'STP', num => '678' },
			    'Saudi Arabia' 					   => { two => 'SA', three =>'SAU', num => '682' },
			    'Senegal' 						   => { two => 'SN', three =>'SEN', num => '686' },
			    'Serbia' 						   => { two => 'RS', three =>'SRB', num => '688' },
			    'Seychelles' 					   => { two => 'SC', three =>'SYC', num => '690' },
			    'Sierra Leone' 					   => { two => 'SL', three =>'SLE', num => '694' },
			    'Singapore' 					   => { two => 'SG', three =>'SGP', num => '702' },
			    'Sint Maarten (Dutch part)' 			   => { two => 'SX', three =>'SXM', num => '534' },
			    'Slovakia' 						   => { two => 'SK', three =>'SVK', num => '703' },
			    'Slovenia' 						   => { two => 'SI', three =>'SVN', num => '705' },
			    'Solomon Islands' 					   => { two => 'SB', three =>'SLB', num => '090' },
			    'Somalia' 						   => { two => 'SO', three =>'SOM', num => '706' },
			    'South Africa' 					   => { two => 'ZA', three =>'ZAF', num => '710' },
			    'South Georgia and the South Sandwich Islands' 	   => { two => 'GS', three =>'SGS', num => '239' },
			    'South Sudan' 					   => { two => 'SS', three =>'SSD', num => '728' },
			    'Spain' 						   => { two => 'ES', three =>'ESP', num => '724' },
			    'Sri Lanka' 					   => { two => 'LK', three =>'LKA', num => '144' },
			    'Sudan' 						   => { two => 'SD', three =>'SDN', num => '729' },
			    'Suriname' 						   => { two => 'SR', three =>'SUR', num => '740' },
			    'Svalbard and Jan Mayen' 				   => { two => 'SJ', three =>'SJM', num => '744' },
			    'Eswatini' 						   => { two => 'SZ', three =>'SWZ', num => '748' },
			    'Sweden' 						   => { two => 'SE', three =>'SWE', num => '752' },
			    'Switzerland' 					   => { two => 'CH', three =>'CHE', num => '756' },
			    'Syrian Arab Republic' 				   => { two => 'SY', three =>'SYR', num => '760' },
			    'Taiwan' 						   => { two => 'TW', three =>'TWN', num => '158' },
			    'Tajikistan' 					   => { two => 'TJ', three =>'TJK', num => '762' },
			    'Tanzania United Republic of' 			   => { two => 'TZ', three =>'TZA', num => '834' },
			    'Thailand' 						   => { two => 'TH', three =>'THA', num => '764' },
			    'Timor-Leste' 					   => { two => 'TL', three =>'TLS', num => '626' },
			    'Togo' 						   => { two => 'TG', three =>'TGO', num => '768' },
			    'Tokelau' 						   => { two => 'TK', three =>'TKL', num => '772' },
			    'Tonga' 						   => { two => 'TO', three =>'TON', num => '776' },
			    'Trinidad and Tobago' 				   => { two => 'TT', three =>'TTO', num => '780' },
			    'Tunisia' 						   => { two => 'TN', three =>'TUN', num => '788' },
			    'Turkey' 						   => { two => 'TR', three =>'TUR', num => '792' },
			    'Turkmenistan' 					   => { two => 'TM', three =>'TKM', num => '795' },
			    'Turks and Caicos Islands' 				   => { two => 'TC', three =>'TCA', num => '796' },
			    'Tuvalu' 						   => { two => 'TV', three =>'TUV', num => '798' },
			    'Uganda' 						   => { two => 'UG', three =>'UGA', num => '800' },
			    'Ukraine' 						   => { two => 'UA', three =>'UKR', num => '804' },
			    'United Arab Emirates' 				   => { two => 'AE', three =>'ARE', num => '784' },
			    'United Kingdom of Great Britain and Northern Ireland' => { two => 'GB', three =>'GBR', num => '826' },
			    'United States of America' 				   => { two => 'US', three =>'USA', num => '840' },
			    'United States Minor Outlying Islands' 		   => { two => 'UM', three =>'UMI', num => '581' },
			    'Uruguay' 						   => { two => 'UY', three =>'URY', num => '858' },
			    'Uzbekistan' 					   => { two => 'UZ', three =>'UZB', num => '860' },
			    'Vanuatu' 						   => { two => 'VU', three =>'VUT', num => '548' },
			    'Venezuela, Bolivarian Republic of' 		   => { two => 'VE', three =>'VEN', num => '862' },
			    'Viet Nam' 						   => { two => 'VN', three =>'VNM', num => '704' },
			    'Virgin Islands (British)' 				   => { two => 'VG', three =>'VGB', num => '092' },
			    'Virgin Islands (U.S.)' 				   => { two => 'VI', three =>'VIR', num => '850' },
			    'Wallis and Futuna' 				   => { two => 'WF', three =>'WLF', num => '876' },
			    'Western Sahara' 					   => { two => 'EH', three =>'ESH', num => '732' },
			    'Yemen' 						   => { two => 'YE', three =>'YEM', num => '887' },
			    'Zambia' 						   => { two => 'ZM', three =>'ZMB', num => '894' },
			    'Zimbabwe'                                             => { two => 'ZW', three =>'ZWE', num => '716' },
			   }
	     };

1;
